<a href="https://colab.research.google.com/github/juszhou/NYUML/blob/main/Copy_of_Mini_Project_Fish_Weight.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
  import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.preprocessing import PolynomialFeatures

In [ ]:
feature = pd.read_csv('https://raw.githubusercontent.com/BolunDai0216/NYUMLSummerSchool21/main/day05/fish_market_feature.csv')
label = pd.read_csv('https://raw.githubusercontent.com/BolunDai0216/NYUMLSummerSchool21/main/day05/fish_market_label.csv')
X = feature.values
y = label.values

feature.head(5)


Length1  Length2  Length3   Height   Width
0     11.7     12.4     13.5   2.4300  1.2690
1     19.0     20.7     23.2   9.3960  3.4104
2     38.0     41.0     46.5  17.6235  6.3705
3     13.2     14.3     15.2   2.8728  2.0672
4     37.3     40.0     43.5  12.3540  6.5250

In [ ]:
label.head(5)

Weight
0    13.4
1   170.0
2   950.0
3    19.7
4  1000.0

In [ ]:
X.shape, y.shape

((124, 5), (124, 1))

In [ ]:
Xtrain, Xval, Ytrain, Yval = train_test_split(X, y, test_size=0.2)

In [ ]:
Xtrain.shape
print(enumerate([1, 2, 5]))

In [ ]:

def design_matrix(x, z, Mx, Mz):
    # 1. create the empty array of ones
    ones = np.ones((x.shape[0],1))
    Design_Matrix_x = np.ones((x.shape[0],Mx))  # use the np.ones function
    Design_Matrix_z = np.ones((x.shape[0],Mz))
    
    # 2. use a for loop to populate the Design_Matrix columnwise
    for i, j in enumerate([1, 2, 5]):
        Design_Matrix_x[:,i] = x**j  # provide an expression for each column of Design_Matrix
    for i, j in enumerate([1, 3]):
        Design_Matrix_z[:,i] = z**j
        
    Design_Matrix = np.hstack((Design_Matrix_x, Design_Matrix_z))
    Design_Matrix = np.hstack((ones, Design_Matrix))
    
    return Design_Matrix


x = np.arange(10)  # x = [0, 1, 2, 3, ..., 99]
z = np.arange(1,11)  # z = [0, 1, 2, 3, ..., 99]
Design_Matrix = design_matrix(x, z, 3, 2) 
print(Design_Matrix)

[[1.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 1.0000e+00 1.0000e+00]
 [1.0000e+00 1.0000e+00 1.0000e+00 1.0000e+00 2.0000e+00 8.0000e+00]
 [1.0000e+00 2.0000e+00 4.0000e+00 3.2000e+01 3.0000e+00 2.7000e+01]
 [1.0000e+00 3.0000e+00 9.0000e+00 2.4300e+02 4.0000e+00 6.4000e+01]
 [1.0000e+00 4.0000e+00 1.6000e+01 1.0240e+03 5.0000e+00 1.2500e+02]
 [1.0000e+00 5.0000e+00 2.5000e+01 3.1250e+03 6.0000e+00 2.1600e+02]
 [1.0000e+00 6.0000e+00 3.6000e+01 7.7760e+03 7.0000e+00 3.4300e+02]
 [1.0000e+00 7.0000e+00 4.9000e+01 1.6807e+04 8.0000e+00 5.1200e+02]
 [1.0000e+00 8.0000e+00 6.4000e+01 3.2768e+04 9.0000e+00 7.2900e+02]
 [1.0000e+00 9.0000e+00 8.1000e+01 5.9049e+04 1.0000e+01 1.0000e+03]]


In [ ]:

def design_matrix(a,b,c,d,e, Ma, Mb, Mc,Md, Me):
    # 1. create the empty array of ones
    ones = np.ones((a.shape[0],5))
    Design_Matrix_a = np.ones((x.shape[0],Ma))  # use the np.ones function
    Design_Matrix_b = np.ones((x.shape[0],Mb))
    Design_Matrix_c = np.ones((x.shape[0],Mc))  # use the np.ones function
    Design_Matrix_d = np.ones((x.shape[0],Md))
    Design_Matrix_e = np.ones((x.shape[0],Me))  # use the np.ones function

    # 2. use a for loop to populate the Design_Matrix columnwise
    for i, j in enumerate(np.arange(1,Ma+1)):
        Design_Matrix_a[:,i] = a**j  # provide an expression for each column of Design_Matrix
    for i, j in enumerate(np.arange(1,Mb+1)):
        Design_Matrix_b[:,i] = b**j
    for i, j in enumerate(np.arange(1,Mc+1)):
        Design_Matrix_c[:,i] = c**j  # provide an expression for each column of Design_Matrix
    for i, j in enumerate(np.arange(1,Md+1)):
        Design_Matrix_d[:,i] = d**j        
    for i, j in enumerate(np.arange(1,Me+1)):
        Design_Matrix_e[:,i] = e**j  # provide an expression for each column of Design_Matrix


    Design_Matrix = np.hstack((Design_Matrix_a, Design_Matrix_b,Design_Matrix_c, Design_Matrix_d,Design_Matrix_e))
    Design_Matrix = np.hstack((ones, Design_Matrix))
    
    return Design_Matrix


x = np.arange(10)  # x = [0, 1, 2, 3, ..., 99]
z = np.arange(1,11)  # z = [0, 1, 2, 3, ..., 99]
Design_Matrix = design_matrix(x, x, x, x, x, 5,5,5,5,5) 
print(Design_Matrix)

NameError: ignored

In [ ]:
# Fit Data (use linear regression, LASSO or rigde regression)
poly = PolynomialFeatures(20)
XtrainNew = poly.fit_transform(Xtrain)
XvalNew = poly.fit_transform(Xval)
reg = linear_model.Lasso(tol=0.04)
reg.fit(XtrainNew, Ytrain)
y_train_pred = reg.predict(XtrainNew)
y_val_pred = reg.predict(XvalNew)

XtrainNew.shape

In [ ]:
# Get MSE

mseTrain = mean_squared_error(Ytrain, y_train_pred)
maeTrain = mean_absolute_error(Ytrain, y_train_pred)

print(f"Training MSE: {mseTrain}")
print(f"Training MAE: {maeTrain}")

mseVal = mean_squared_error(Yval, y_val_pred)
maeVal = mean_absolute_error(Yval, y_val_pred)

print(f"Validation MSE: {mseVal}")
print(f"Validation MAE: {maeVal}")

**Linear Regression(2nd order):** \\
  Training MSE: 2098.652147298266 \\
  Training MAE: 31.54300123719605 \\
  Validation MSE: 1873.2185203114227 \\
  Validation MAE: 29.84940607793905